### ISSUE TITLE
Share MDN Example Not Working - TypeError: navigator.share is not a function

### ISSUE THREAD

**Issue by jamiehewitt15** [mdn/content#23403]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

### What specific section or headline is this issue about?

Result

### What information was incorrect, unhelpful, or incomplete?

From my understanding after reading this page, the `Share MDN` example button should work on Chrome (Version 108.0.5359.124). However, when I click it  I get the following error message: 

![image](https://user-images.githubusercontent.com/20739535/210777103-ed877219-939c-445b-a05c-b3ef44d2253e.png)

### What did you expect to see?

I expected to see the share button working. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/share`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/share/index.md
* Last commit: https://github.com/mdn/content/commit/af967bb052695baa631c004b9b149c6f91920776
* Document last modified: 2022-12-12T20:23:34.000Z

</details>

**Comment by sideshowbarker** [comment]
This is most likely due to the code not being run in a secure context (from an https URL).

**Comment by jamiehewitt15** [comment]
> This is most likely due to the code not being run in a secure context (from an https URL).

I was using it on the `https://developer.mozilla.org/` site which is using `https`, so it presumably it should work?

![mdn - share](https://user-images.githubusercontent.com/20739535/210784676-48d1a088-308a-4af5-b22f-d9e1df483de2.png)

**Comment by wbamberg** [comment]
I'll make a quick PR to test the theory!

**Comment by wbamberg** [comment]
Well apparently I'm wrong, or at least `{{EmbedLiveSample('Sharing a URL', "", "", "", "", "", "web-share")}}` does not make it work...

**Comment by hamishwillee** [comment]
Works for me 108.0.5359.125
![image](https://user-images.githubusercontent.com/5368500/210894390-8fcc4d28-095e-4459-b7b6-7eab59712866.png)

**Comment by jamiehewitt15** [comment]
I think this must be an operating system issue. I tested it on my Android phone and it works fine and it works for @hamishwillee on Windows.

However, I've tested it with various browsers on Ubuntu 22.04.1 LTS and none of them work: 
- Firefox 108.0.2 
- Chromium 108.0.5359.124 (Official Build) snap (64-bit)
- Brave Version 1.46.144 
- Chrome 108.0.5359.124

I also tested each of those browsers in an incognito window and they still didn't work.

**Comment by jamiehewitt15** [comment]
Related issues:

- https://github.com/mdn/browser-compat-data/issues/16247
- https://github.com/mdn/browser-compat-data/issues/12396
- https://github.com/mdn/browser-compat-data/issues/16326

**Comment by wbamberg** [comment]
I believe BCD now shows (more) correct information since https://github.com/mdn/browser-compat-data/pull/18857.

-> https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility

**Comment by jamiehewitt15** [comment]
So only works on Windows and Chrome OS?

**Comment by tiagorangel2011** [comment]
Not working on Windows 11 firefox.
Error: TypeError: navigator.share is not a function

**Comment by hamishwillee** [comment]
> Not working on Windows 11 firefox.
> Error: TypeError: navigator.share is not a function

For firefox the feature is behind a preference, so this is expected.
